### ISSUE TITLE
Can't Download

### ISSUE THREAD

**Issue by duke912** [eqprog/FF7CCUP#11]
At around 1gb download I get an error and need to restart from beggining, already tried 3 times in a row,  can you upload it to another server than sh*thub?

**Comment by eqprog** [comment]
Sure, I am not at home right now but I should be able to upload it somewhere later on tonight. (CST)

**Comment by eqprog** [comment]
https://drive.google.com/file/d/1Xj4KSkRlcfxIlmmRYiCLhOmc4P6A_-Kw/view?usp=sharing

**Comment by eqprog** [comment]
I put an updated link in the readme on the repo. I’ll try to keep it updated as we make progress.
