### ISSUE TITLE
No TEXTURES repository

### ISSUE THREAD

**Issue by Infinity-MaxX** [eqprog/FF7CCUP#19]
So, you're saying you need to install it into "Users\[name]\Documents\PPSSPP\PSP\TEXTURES\ULUS10336\". However, there is no repository named "TEXTURES" under "PSP", so I'm a little unsure of how to install this package.

edit: Well, there IS on the Android version but not the PC version.

**Comment by DevinaGithub** [comment]
I updated the readme, try the second method instead.

**Comment by Infinity-MaxX** [comment]
I feel like I might have done something wrong from the beginning when installing PPSSPP (except I've just reinstalled it and nothing has changed). And now I just feel stupid.

I don't have the second method either. My list when entering the PPSSPP directory in Documents only has the PSP directory. And the PSP directory only has: COMMON, GAME, PPSSPP_STATE, SAVEDATA, and SYSTEM. Of those five folders, only GAMES and SYSTEM has additional material, with SYSTEM only having two files (controls and ppsspp) and a folder named CACHE D:
