### ISSUE TITLE
Weird textures

### ISSUE THREAD

**Issue by Infinity-MaxX** [eqprog/FF7CCUP#20]
I managed to figure out how to make it all work. So sorry for... well, practically wasting your time.

Anyway. I've been restarting the game a lot of times just messing around with the settings and I guess it's made me a bit perceptive to the texture changes. I've... found and taken screenshots of instances where the texture looks odd or otherwise... inconsistent with the new textures you've added. But... how do I share that sort of thing with you guys? _Is_ there a way for others to send you guys instances for when the texture is looking funny?

I can upload the one image I have so far, here, but... for future references, I suppose, another place might be better. 

The below image has some weird walls behind Zack, especially the parts with the blue-turquoise light -- the texture doesn't look upscaled -- and Kunsel's shoulder pads looks... "leathery or gummi-like". The metal disk on his back is a little unclear for me, but I remember that was a thing you spotted for Zack over on the forum rather late, so I thought I might as well mention it.
![Untitled #1](https://user-images.githubusercontent.com/46093609/98448584-577d3380-212d-11eb-9763-f3d619b572db.png)

Hope I'm not bothering you guys with this, you've done such a fantastic job with improving the quality of this game :)

**Comment by eqprog** [comment]
Its something that is being worked on over time. The AI isn't perfect and requires manual editing.
